// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Message.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_MessageType int32

const (
	Message_COMMAND          Message_MessageType = 0
	Message_COMMAND_RESPONSE Message_MessageType = 1
	Message_FILE_REQUEST     Message_MessageType = 2
	Message_FILE_CHUNK       Message_MessageType = 3
	Message_PING             Message_MessageType = 4
	Message_PING_RESPONSE    Message_MessageType = 5
	Message_LEAVE            Message_MessageType = 6
	Message_FIND_NODE        Message_MessageType = 7
	Message_FOUND_NODES      Message_MessageType = 8
)

var Message_MessageType_name = map[int32]string{
	0: "COMMAND",
	1: "COMMAND_RESPONSE",
	2: "FILE_REQUEST",
	3: "FILE_CHUNK",
	4: "PING",
	5: "PING_RESPONSE",
	6: "LEAVE",
	7: "FIND_NODE",
	8: "FOUND_NODES",
}
var Message_MessageType_value = map[string]int32{
	"COMMAND":          0,
	"COMMAND_RESPONSE": 1,
	"FILE_REQUEST":     2,
	"FILE_CHUNK":       3,
	"PING":             4,
	"PING_RESPONSE":    5,
	"LEAVE":            6,
	"FIND_NODE":        7,
	"FOUND_NODES":      8,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}
func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Message_1378cd04d204e8da, []int{0, 0}
}

type Message_Status int32

const (
	Message_FAIL Message_Status = 0
	Message_OK   Message_Status = 1
)

var Message_Status_name = map[int32]string{
	0: "FAIL",
	1: "OK",
}
var Message_Status_value = map[string]int32{
	"FAIL": 0,
	"OK":   1,
}

func (x Message_Status) String() string {
	return proto.EnumName(Message_Status_name, int32(x))
}
func (Message_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Message_1378cd04d204e8da, []int{0, 1}
}

type Message struct {
	Uuid      string              `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Type      Message_MessageType `protobuf:"varint,2,opt,name=type,enum=botnet_p2p.Message_MessageType" json:"type,omitempty"`
	Sender    *Message_Contact    `protobuf:"bytes,3,opt,name=sender" json:"sender,omitempty"`
	Receiver  *Message_Contact    `protobuf:"bytes,4,opt,name=receiver" json:"receiver,omitempty"`
	Propagate bool                `protobuf:"varint,5,opt,name=propagate" json:"propagate,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*Message_Command
	//	*Message_Response
	//	*Message_FileRequest
	//	*Message_FileChunk
	//	*Message_FindNode
	//	*Message_FoundNodes
	Payload              isMessage_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_1378cd04d204e8da, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_Command struct {
	Command *Message_CommandMsg `protobuf:"bytes,6,opt,name=command,oneof"`
}
type Message_Response struct {
	Response *Message_CommandResponseMsg `protobuf:"bytes,7,opt,name=response,oneof"`
}
type Message_FileRequest struct {
	FileRequest *Message_FileRequestMsg `protobuf:"bytes,8,opt,name=fileRequest,oneof"`
}
type Message_FileChunk struct {
	FileChunk *Message_FileChunkMsg `protobuf:"bytes,9,opt,name=fileChunk,oneof"`
}
type Message_FindNode struct {
	FindNode *Message_FindNodeMsg `protobuf:"bytes,10,opt,name=findNode,oneof"`
}
type Message_FoundNodes struct {
	FoundNodes *Message_FoundNodesMsg `protobuf:"bytes,11,opt,name=foundNodes,oneof"`
}

func (*Message_Command) isMessage_Payload()     {}
func (*Message_Response) isMessage_Payload()    {}
func (*Message_FileRequest) isMessage_Payload() {}
func (*Message_FileChunk) isMessage_Payload()   {}
func (*Message_FindNode) isMessage_Payload()    {}
func (*Message_FoundNodes) isMessage_Payload()  {}

func (m *Message) GetPayload() isMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Message) GetType() Message_MessageType {
	if m != nil {
		return m.Type
	}
	return Message_COMMAND
}

func (m *Message) GetSender() *Message_Contact {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Message) GetReceiver() *Message_Contact {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *Message) GetPropagate() bool {
	if m != nil {
		return m.Propagate
	}
	return false
}

func (m *Message) GetCommand() *Message_CommandMsg {
	if x, ok := m.GetPayload().(*Message_Command); ok {
		return x.Command
	}
	return nil
}

func (m *Message) GetResponse() *Message_CommandResponseMsg {
	if x, ok := m.GetPayload().(*Message_Response); ok {
		return x.Response
	}
	return nil
}

func (m *Message) GetFileRequest() *Message_FileRequestMsg {
	if x, ok := m.GetPayload().(*Message_FileRequest); ok {
		return x.FileRequest
	}
	return nil
}

func (m *Message) GetFileChunk() *Message_FileChunkMsg {
	if x, ok := m.GetPayload().(*Message_FileChunk); ok {
		return x.FileChunk
	}
	return nil
}

func (m *Message) GetFindNode() *Message_FindNodeMsg {
	if x, ok := m.GetPayload().(*Message_FindNode); ok {
		return x.FindNode
	}
	return nil
}

func (m *Message) GetFoundNodes() *Message_FoundNodesMsg {
	if x, ok := m.GetPayload().(*Message_FoundNodes); ok {
		return x.FoundNodes
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_Command)(nil),
		(*Message_Response)(nil),
		(*Message_FileRequest)(nil),
		(*Message_FileChunk)(nil),
		(*Message_FindNode)(nil),
		(*Message_FoundNodes)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// payload
	switch x := m.Payload.(type) {
	case *Message_Command:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Command); err != nil {
			return err
		}
	case *Message_Response:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Response); err != nil {
			return err
		}
	case *Message_FileRequest:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FileRequest); err != nil {
			return err
		}
	case *Message_FileChunk:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FileChunk); err != nil {
			return err
		}
	case *Message_FindNode:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FindNode); err != nil {
			return err
		}
	case *Message_FoundNodes:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FoundNodes); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.Payload has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 6: // payload.command
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Message_CommandMsg)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_Command{msg}
		return true, err
	case 7: // payload.response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Message_CommandResponseMsg)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_Response{msg}
		return true, err
	case 8: // payload.fileRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Message_FileRequestMsg)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_FileRequest{msg}
		return true, err
	case 9: // payload.fileChunk
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Message_FileChunkMsg)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_FileChunk{msg}
		return true, err
	case 10: // payload.findNode
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Message_FindNodeMsg)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_FindNode{msg}
		return true, err
	case 11: // payload.foundNodes
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Message_FoundNodesMsg)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_FoundNodes{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// payload
	switch x := m.Payload.(type) {
	case *Message_Command:
		s := proto.Size(x.Command)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Response:
		s := proto.Size(x.Response)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_FileRequest:
		s := proto.Size(x.FileRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_FileChunk:
		s := proto.Size(x.FileChunk)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_FindNode:
		s := proto.Size(x.FindNode)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_FoundNodes:
		s := proto.Size(x.FoundNodes)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Message_Contact struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid" json:"guid,omitempty"`
	IP                   string   `protobuf:"bytes,2,opt,name=IP" json:"IP,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	IsNAT                bool     `protobuf:"varint,4,opt,name=isNAT" json:"isNAT,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_Contact) Reset()         { *m = Message_Contact{} }
func (m *Message_Contact) String() string { return proto.CompactTextString(m) }
func (*Message_Contact) ProtoMessage()    {}
func (*Message_Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_1378cd04d204e8da, []int{0, 0}
}
func (m *Message_Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Contact.Unmarshal(m, b)
}
func (m *Message_Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Contact.Marshal(b, m, deterministic)
}
func (dst *Message_Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Contact.Merge(dst, src)
}
func (m *Message_Contact) XXX_Size() int {
	return xxx_messageInfo_Message_Contact.Size(m)
}
func (m *Message_Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Contact proto.InternalMessageInfo

func (m *Message_Contact) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *Message_Contact) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *Message_Contact) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Message_Contact) GetIsNAT() bool {
	if m != nil {
		return m.IsNAT
	}
	return false
}

type Message_CommandMsg struct {
	Command              string   `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	ShouldRespond        bool     `protobuf:"varint,2,opt,name=shouldRespond" json:"shouldRespond,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_CommandMsg) Reset()         { *m = Message_CommandMsg{} }
func (m *Message_CommandMsg) String() string { return proto.CompactTextString(m) }
func (*Message_CommandMsg) ProtoMessage()    {}
func (*Message_CommandMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_1378cd04d204e8da, []int{0, 1}
}
func (m *Message_CommandMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_CommandMsg.Unmarshal(m, b)
}
func (m *Message_CommandMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_CommandMsg.Marshal(b, m, deterministic)
}
func (dst *Message_CommandMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_CommandMsg.Merge(dst, src)
}
func (m *Message_CommandMsg) XXX_Size() int {
	return xxx_messageInfo_Message_CommandMsg.Size(m)
}
func (m *Message_CommandMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_CommandMsg.DiscardUnknown(m)
}

var xxx_messageInfo_Message_CommandMsg proto.InternalMessageInfo

func (m *Message_CommandMsg) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Message_CommandMsg) GetShouldRespond() bool {
	if m != nil {
		return m.ShouldRespond
	}
	return false
}

type Message_CommandResponseMsg struct {
	Value                string         `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	Status               Message_Status `protobuf:"varint,2,opt,name=status,enum=botnet_p2p.Message_Status" json:"status,omitempty"`
	Command              string         `protobuf:"bytes,3,opt,name=command" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Message_CommandResponseMsg) Reset()         { *m = Message_CommandResponseMsg{} }
func (m *Message_CommandResponseMsg) String() string { return proto.CompactTextString(m) }
func (*Message_CommandResponseMsg) ProtoMessage()    {}
func (*Message_CommandResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_1378cd04d204e8da, []int{0, 2}
}
func (m *Message_CommandResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_CommandResponseMsg.Unmarshal(m, b)
}
func (m *Message_CommandResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_CommandResponseMsg.Marshal(b, m, deterministic)
}
func (dst *Message_CommandResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_CommandResponseMsg.Merge(dst, src)
}
func (m *Message_CommandResponseMsg) XXX_Size() int {
	return xxx_messageInfo_Message_CommandResponseMsg.Size(m)
}
func (m *Message_CommandResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_CommandResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_Message_CommandResponseMsg proto.InternalMessageInfo

func (m *Message_CommandResponseMsg) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Message_CommandResponseMsg) GetStatus() Message_Status {
	if m != nil {
		return m.Status
	}
	return Message_FAIL
}

func (m *Message_CommandResponseMsg) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

type Message_FileRequestMsg struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_FileRequestMsg) Reset()         { *m = Message_FileRequestMsg{} }
func (m *Message_FileRequestMsg) String() string { return proto.CompactTextString(m) }
func (*Message_FileRequestMsg) ProtoMessage()    {}
func (*Message_FileRequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_1378cd04d204e8da, []int{0, 3}
}
func (m *Message_FileRequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_FileRequestMsg.Unmarshal(m, b)
}
func (m *Message_FileRequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_FileRequestMsg.Marshal(b, m, deterministic)
}
func (dst *Message_FileRequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_FileRequestMsg.Merge(dst, src)
}
func (m *Message_FileRequestMsg) XXX_Size() int {
	return xxx_messageInfo_Message_FileRequestMsg.Size(m)
}
func (m *Message_FileRequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_FileRequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_Message_FileRequestMsg proto.InternalMessageInfo

func (m *Message_FileRequestMsg) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Message_FileChunkMsg struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=fileName" json:"fileName,omitempty"`
	FileSize             uint32   `protobuf:"varint,3,opt,name=fileSize" json:"fileSize,omitempty"`
	Ordinal              uint32   `protobuf:"varint,4,opt,name=ordinal" json:"ordinal,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_FileChunkMsg) Reset()         { *m = Message_FileChunkMsg{} }
func (m *Message_FileChunkMsg) String() string { return proto.CompactTextString(m) }
func (*Message_FileChunkMsg) ProtoMessage()    {}
func (*Message_FileChunkMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_1378cd04d204e8da, []int{0, 4}
}
func (m *Message_FileChunkMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_FileChunkMsg.Unmarshal(m, b)
}
func (m *Message_FileChunkMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_FileChunkMsg.Marshal(b, m, deterministic)
}
func (dst *Message_FileChunkMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_FileChunkMsg.Merge(dst, src)
}
func (m *Message_FileChunkMsg) XXX_Size() int {
	return xxx_messageInfo_Message_FileChunkMsg.Size(m)
}
func (m *Message_FileChunkMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_FileChunkMsg.DiscardUnknown(m)
}

var xxx_messageInfo_Message_FileChunkMsg proto.InternalMessageInfo

func (m *Message_FileChunkMsg) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Message_FileChunkMsg) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *Message_FileChunkMsg) GetFileSize() uint32 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *Message_FileChunkMsg) GetOrdinal() uint32 {
	if m != nil {
		return m.Ordinal
	}
	return 0
}

func (m *Message_FileChunkMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Message_FindNodeMsg struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid" json:"guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_FindNodeMsg) Reset()         { *m = Message_FindNodeMsg{} }
func (m *Message_FindNodeMsg) String() string { return proto.CompactTextString(m) }
func (*Message_FindNodeMsg) ProtoMessage()    {}
func (*Message_FindNodeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_1378cd04d204e8da, []int{0, 5}
}
func (m *Message_FindNodeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_FindNodeMsg.Unmarshal(m, b)
}
func (m *Message_FindNodeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_FindNodeMsg.Marshal(b, m, deterministic)
}
func (dst *Message_FindNodeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_FindNodeMsg.Merge(dst, src)
}
func (m *Message_FindNodeMsg) XXX_Size() int {
	return xxx_messageInfo_Message_FindNodeMsg.Size(m)
}
func (m *Message_FindNodeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_FindNodeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_Message_FindNodeMsg proto.InternalMessageInfo

func (m *Message_FindNodeMsg) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

type Message_FoundNodesMsg struct {
	Nodes                []*Message_Contact `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Message_FoundNodesMsg) Reset()         { *m = Message_FoundNodesMsg{} }
func (m *Message_FoundNodesMsg) String() string { return proto.CompactTextString(m) }
func (*Message_FoundNodesMsg) ProtoMessage()    {}
func (*Message_FoundNodesMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_1378cd04d204e8da, []int{0, 6}
}
func (m *Message_FoundNodesMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_FoundNodesMsg.Unmarshal(m, b)
}
func (m *Message_FoundNodesMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_FoundNodesMsg.Marshal(b, m, deterministic)
}
func (dst *Message_FoundNodesMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_FoundNodesMsg.Merge(dst, src)
}
func (m *Message_FoundNodesMsg) XXX_Size() int {
	return xxx_messageInfo_Message_FoundNodesMsg.Size(m)
}
func (m *Message_FoundNodesMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_FoundNodesMsg.DiscardUnknown(m)
}

var xxx_messageInfo_Message_FoundNodesMsg proto.InternalMessageInfo

func (m *Message_FoundNodesMsg) GetNodes() []*Message_Contact {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "botnet_p2p.Message")
	proto.RegisterType((*Message_Contact)(nil), "botnet_p2p.Message.Contact")
	proto.RegisterType((*Message_CommandMsg)(nil), "botnet_p2p.Message.CommandMsg")
	proto.RegisterType((*Message_CommandResponseMsg)(nil), "botnet_p2p.Message.CommandResponseMsg")
	proto.RegisterType((*Message_FileRequestMsg)(nil), "botnet_p2p.Message.FileRequestMsg")
	proto.RegisterType((*Message_FileChunkMsg)(nil), "botnet_p2p.Message.FileChunkMsg")
	proto.RegisterType((*Message_FindNodeMsg)(nil), "botnet_p2p.Message.FindNodeMsg")
	proto.RegisterType((*Message_FoundNodesMsg)(nil), "botnet_p2p.Message.FoundNodesMsg")
	proto.RegisterEnum("botnet_p2p.Message_MessageType", Message_MessageType_name, Message_MessageType_value)
	proto.RegisterEnum("botnet_p2p.Message_Status", Message_Status_name, Message_Status_value)
}

func init() { proto.RegisterFile("Message.proto", fileDescriptor_Message_1378cd04d204e8da) }

var fileDescriptor_Message_1378cd04d204e8da = []byte{
	// 666 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xad, 0xf3, 0xb4, 0xaf, 0xeb, 0x60, 0xae, 0xba, 0xb0, 0x0c, 0xa2, 0x69, 0x54, 0xa1, 0xac,
	0x2a, 0x91, 0x2e, 0x90, 0x90, 0x90, 0x48, 0x13, 0x87, 0x46, 0x4d, 0x9c, 0x30, 0x69, 0x61, 0x19,
	0x4d, 0xeb, 0x69, 0x6a, 0x91, 0xda, 0xc6, 0x8f, 0x8a, 0xf2, 0x05, 0x7c, 0x03, 0xbf, 0xc8, 0x4f,
	0x20, 0x8f, 0x27, 0xb1, 0x23, 0x0c, 0x5d, 0xe5, 0xde, 0xf1, 0x39, 0x67, 0x26, 0xf7, 0x9c, 0x19,
	0xd0, 0xa6, 0x2c, 0x8a, 0xe8, 0x8a, 0x9d, 0x04, 0xa1, 0x1f, 0xfb, 0x08, 0xd7, 0x7e, 0xec, 0xb1,
	0x78, 0x19, 0xf4, 0x82, 0xce, 0x6f, 0x80, 0xa6, 0xf8, 0x8a, 0x08, 0xb5, 0x24, 0x71, 0x1d, 0x43,
	0x6a, 0x4b, 0x5d, 0x85, 0xf0, 0x1a, 0x4f, 0xa1, 0x16, 0x3f, 0x06, 0xcc, 0xa8, 0xb4, 0xa5, 0x6e,
	0xab, 0x77, 0x78, 0x92, 0x53, 0x4f, 0x36, 0xa2, 0xe2, 0xf7, 0xf2, 0x31, 0x60, 0x84, 0x83, 0xf1,
	0x14, 0x1a, 0x11, 0xf3, 0x1c, 0x16, 0x1a, 0xd5, 0xb6, 0xd4, 0x55, 0x7b, 0x2f, 0xca, 0x68, 0x03,
	0xdf, 0x8b, 0xe9, 0x4d, 0x4c, 0x04, 0x14, 0xdf, 0x82, 0x1c, 0xb2, 0x1b, 0xe6, 0x3e, 0xb0, 0xd0,
	0xa8, 0x3d, 0x4d, 0xdb, 0x82, 0xf1, 0x25, 0x28, 0x41, 0xe8, 0x07, 0x74, 0x45, 0x63, 0x66, 0xd4,
	0xdb, 0x52, 0x57, 0x26, 0xf9, 0x02, 0xbe, 0x83, 0xe6, 0x8d, 0x7f, 0x7f, 0x4f, 0x3d, 0xc7, 0x68,
	0x70, 0xd5, 0x57, 0xe5, 0xaa, 0x1c, 0x32, 0x8d, 0x56, 0xe7, 0x7b, 0x64, 0x43, 0xc0, 0x61, 0x7a,
	0xa4, 0x28, 0xf0, 0xbd, 0x88, 0x19, 0x4d, 0x4e, 0x7e, 0xfd, 0x1f, 0x32, 0x11, 0xd0, 0x4c, 0x64,
	0xcb, 0xc4, 0x11, 0xa8, 0xb7, 0xee, 0x9a, 0x11, 0xf6, 0x2d, 0x61, 0x51, 0x6c, 0xc8, 0x5c, 0xa8,
	0x53, 0x26, 0x34, 0xca, 0x61, 0x99, 0x48, 0x91, 0x88, 0x1f, 0x40, 0x49, 0xdb, 0xc1, 0x5d, 0xe2,
	0x7d, 0x35, 0x14, 0xae, 0xd2, 0xfe, 0x97, 0x0a, 0x07, 0x65, 0x1a, 0x39, 0x09, 0xdf, 0x83, 0x7c,
	0xeb, 0x7a, 0x8e, 0xed, 0x3b, 0xcc, 0x00, 0x2e, 0x70, 0x58, 0x2e, 0x90, 0x61, 0xc4, 0x1f, 0xd9,
	0x50, 0x70, 0x00, 0x70, 0xeb, 0x27, 0x59, 0x13, 0x19, 0x2a, 0x17, 0x38, 0x2a, 0x15, 0xd8, 0xa2,
	0x32, 0x89, 0x02, 0xcd, 0xfc, 0x02, 0x4d, 0x61, 0x61, 0x9a, 0xb7, 0x55, 0x21, 0x6f, 0x69, 0x8d,
	0x2d, 0xa8, 0x8c, 0xe7, 0x3c, 0x6d, 0x0a, 0xa9, 0x8c, 0xe7, 0x29, 0x26, 0xf0, 0xc3, 0x98, 0x07,
	0x49, 0x23, 0xbc, 0xc6, 0x03, 0xa8, 0xbb, 0x91, 0xdd, 0xbf, 0xe4, 0x31, 0x91, 0x49, 0xd6, 0x98,
	0x13, 0x80, 0xdc, 0x45, 0x34, 0x72, 0xdb, 0x33, 0xf9, 0xad, 0xa9, 0xc7, 0xa0, 0x45, 0x77, 0x7e,
	0xb2, 0x16, 0x7e, 0x39, 0x7c, 0x33, 0x99, 0xec, 0x2e, 0x9a, 0xdf, 0x01, 0xff, 0xb6, 0x35, 0xdd,
	0xf9, 0x81, 0xae, 0x13, 0x26, 0x34, 0xb3, 0x06, 0x7b, 0xd0, 0x88, 0x62, 0x1a, 0x27, 0x91, 0xb8,
	0x25, 0x66, 0xd9, 0x4c, 0x16, 0x1c, 0x41, 0x04, 0xb2, 0x78, 0xbe, 0xea, 0xce, 0xf9, 0xcc, 0x63,
	0x68, 0xed, 0xe6, 0x80, 0xcf, 0x80, 0xc6, 0x77, 0x9b, 0x39, 0xa5, 0xb5, 0xf9, 0x53, 0x82, 0xfd,
	0xa2, 0xd1, 0xa5, 0x97, 0xd7, 0x4c, 0xfd, 0x5e, 0x33, 0x9b, 0xde, 0x33, 0x31, 0xd2, 0x6d, 0xbf,
	0xf9, 0xb6, 0x70, 0x7f, 0x30, 0x31, 0xdc, 0x6d, 0x9f, 0x1e, 0xce, 0x0f, 0x1d, 0xd7, 0xa3, 0x6b,
	0x3e, 0x62, 0x8d, 0x6c, 0xda, 0x74, 0x17, 0x87, 0xc6, 0x94, 0x5f, 0xb3, 0x7d, 0xc2, 0x6b, 0xf3,
	0x08, 0xd4, 0x42, 0x62, 0xca, 0x5c, 0x35, 0xcf, 0x40, 0xdb, 0xc9, 0x04, 0xbe, 0x81, 0xba, 0xc7,
	0x53, 0x24, 0xb5, 0xab, 0x4f, 0xdd, 0xf4, 0x0c, 0xd9, 0xf9, 0x25, 0x81, 0x5a, 0x78, 0x6a, 0x50,
	0x85, 0xe6, 0x60, 0x36, 0x9d, 0xf6, 0xed, 0xa1, 0xbe, 0x87, 0x07, 0xa0, 0x8b, 0x66, 0x49, 0xac,
	0xc5, 0x7c, 0x66, 0x2f, 0x2c, 0x5d, 0x42, 0x1d, 0xf6, 0x47, 0xe3, 0x89, 0xb5, 0x24, 0xd6, 0xa7,
	0x2b, 0x6b, 0x71, 0xa9, 0x57, 0xb0, 0x05, 0xc0, 0x57, 0x06, 0xe7, 0x57, 0xf6, 0x85, 0x5e, 0x45,
	0x19, 0x6a, 0xf3, 0xb1, 0xfd, 0x51, 0xaf, 0xe1, 0x73, 0xd0, 0xd2, 0x2a, 0xa7, 0xd7, 0x51, 0x81,
	0xfa, 0xc4, 0xea, 0x7f, 0xb6, 0xf4, 0x06, 0x6a, 0xa0, 0x8c, 0xc6, 0xf6, 0x70, 0x69, 0xcf, 0x86,
	0x96, 0xde, 0xc4, 0x67, 0xa0, 0x8e, 0x66, 0x57, 0xa2, 0x5f, 0xe8, 0x72, 0xc7, 0x84, 0x46, 0x66,
	0x70, 0xaa, 0x38, 0xea, 0x8f, 0x27, 0xfa, 0x1e, 0x36, 0xa0, 0x32, 0xbb, 0xd0, 0xa5, 0x33, 0x05,
	0x9a, 0x01, 0x7d, 0x5c, 0xfb, 0xd4, 0xb9, 0x6e, 0xf0, 0x07, 0xf8, 0xf4, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x7a, 0x30, 0xf8, 0x0c, 0x91, 0x05, 0x00, 0x00,
}
